from sqlalchemy import Column, Integer, String, DateTime, JSON
from sqlalchemy.dialects.postgresql import UUID
import uuid
from datetime import datetime, timezone
from .database import Base


class Submission(Base):
    __tablename__ = "submissions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String, nullable=False)
    exam_id = Column(String, nullable=False)
    exam_name = Column(String, nullable=False)
    answers = Column(JSON, nullable=False)
    submitted_at = Column(DateTime, nullable=False,
                          default=lambda: datetime.now(timezone.utc))
    status = Column(String, nullable=False)
    summary = Column(String, nullable=False)    # generated by autograder
    feedback = Column(String, nullable=False)   # finalized result
    score = Column(Integer)

    def __repr__(self):
        return f"<Submission(email='{self.email}', exam_id='{self.exam_id}', submitted_at={self.submitted_at})>"
